### PR TITLE
refactoring navigation

### PR DESCRIPTION
**Pull request by MajeedKazemi**
- remove `focusedNode` (and all dependencies to it)
- navigation moves (left/right/up/down as well as clicks and updates after code modifications) will be done through the focus.ts module. This module will be the only module responsible for updating the editor's cursor position and selection. No other module should do these two actions to help with debugging and maintain a clean code.
- the focus.ts contains helper functions such as `getContext()` that would retrieve the full context based on the current selection/focused-position in the editor. the Context will additionally have information about its surrounds to better help with validation.
- the new focus.ts will help us develop a validator.ts module in the future

### CODE REVIEW

**Comment by MajeedKazemi** [comment]
### issues to be fixed:

- able to write text near text-editable items:
image
image
image

- currently working states:
image

**Comment by MajeedKazemi** [comment]
### issues to be fixed:

- the `navigateLeft()` and `navigateRight()` methods should correctly take the user to the prev/next line if at the beginning/end of a line.
- similarly the `navigateUp()` and `navigateDown()` methods should work properly

**Comment by MajeedKazemi** [comment]
### issues to be fixed:

- not able to define variables inside the body of other compound statements (`for`, `while`, `if` and etc.)

**Comment by vicchig** [comment]
**issues to be fixed:**

  1. Toolbox buttons are disabled inside of block statements even though they should be available. This is a problem with the check in tryInsert that looks for statements with bodies. This causes problems with the menu not showing up when needed.

**Comment by MajeedKazemi** [comment]
### issues to be fixed:

- on undefined `removeNotificationFromDOM()`

**Comment by vicchig** [comment]
> 
> ### issues to be fixed:
> 
>     * not able to define variables inside the body of other compound statements (`for`, `while`, `if` and etc.)

I fixed this one. It should work now.

**Comment by vicchig** [comment]
> 
> ### issues to be fixed:
> 
>     * on undefined `removeNotificationFromDOM()`

Do you remember when this happens/what actions you performed?

**Pull request merged**
